language: objective-c

install:
  - brew update
  - brew install pdf2htmlex
  - brew install phantomjs
  - brew install haxe
  - mkdir ~/haxelib && haxelib setup ~/haxelib
  - haxelib install converter.hxml
  - haxelib install chrome.hxml
  - bower install

script:
  - pdf2htmlex data/*.pdf --dest-dir data
  - haxe converter.hxml
  - haxe chrome.hxml
